### ISSUE TITLE
Parquet schema v2

### ISSUE THREAD

**Issue by darthf1** [Jocoon/php-parquet#8]
Hi! 

Thanks for this library. I'm generating parquet files in my code via a python script, and I'm testing the output via your library.

Currently I generate a file with `pyarrow` with a v1 schema. When I generate a file with a v2 schema, the following error is thrown:

```python
import pyarrow.parquet as pq

pq_writer = pq.ParquetWriter(result, schema=pq_schema, version='2.0')
```

```
Exception : encoding 8 is not supported.
 /home/www/app/vendor/jocoon/parquet/src/file/DataColumnReader.php:297
 /home/www/app/vendor/jocoon/parquet/src/file/DataColumnReader.php:217
 /home/www/app/vendor/jocoon/parquet/src/file/DataColumnReader.php:420
 /home/www/app/vendor/jocoon/parquet/src/ParquetRowGroupReader.php:105
```

I'm not sure of how big an ask this is; Is it possible to support the v2 schema?

**Comment by KevinVonJocoon** [comment]
Hello there,
you're getting an error due to:

- the data page uses RLE_DICTIONARY (encoding 8), which is not supported in the current release of php-parquet
- v2 format specs, including the DATA_PAGE_V2, are not fully implemented

To my current knowledge, there's a concern about the 2.0 format specs in the community, as there have been backward-incompatible fixes last year. I see the advantages of DATA_PAGE_V2, as the main difference is the stored definition- and repetition levels are never compressed which makes skipping pages easier and scanning the data faster in some cases.
Additionally, it seems V2-feature support is highly fragmented across multiple parquet libraries (non-PHP).

As far as I can see, the step towards V2-compatibility is DATA_PAGE_V2 and RLE_DICTIONARY support, but my gut feeling tells me, there's more to this.

I'll see what I can do, no ETA. Initial local testing looks good.
@darthf1  Do you have some example files you can provide using various V2-related 'specialties'?

**Comment by KevinVonJocoon** [comment]
Closing due to repository/package changes.
Please migrate to [codename/parquet](https://packagist.org/packages/codename/parquet) and/or see repository at [github.com/codename-hub/php-parquet](https://github.com/codename-hub/php-parquet).

I've prepared improvements to support 2.0 format specs (including DATAPAGE_V2) and some more stuff is to come, not yet released (but you'll find indications in non-master branches there).
